name: Build ZIP on GitHub Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move plugin files into folder and zip
        run: |
          mkdir wemake-acs
          cp -r assets inc languages lib wemake_acs.php wemake-acs/
          zip -r wemake-acs.zip wemake-acs/

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: wemake-acs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # або secrets.GITHUB_TOKEN для public
