name: Build ZIP on GitHub Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move plugin files into folder and zip
        run: |
          mkdir wemake-acs
          shopt -s extglob
          mv !(wemake-acs) wemake-acs/
          zip -r wemake-acs.zip wemake-acs
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: wemake-acs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
