name: Build ZIP on GitHub Release

on:
  release:
    types: [published]

permissions:
  contents: write 
jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create plugin zip
        run: |
          mkdir wemake-acs
          cp -r assets inc languages lib wemake_acs.php wemake-acs/
          zip -r wemake-acs.zip wemake-acs/

      - name: Upload release asset
        uses: softprops/action-gh-release@v2 
        with:
          tag_name: ${{ github.event.release.tag_name }} 
          files: wemake-acs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
